# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_registrationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
